In [3]:
# import gym_examples
# import gym

# env = gym.make('gym_examples/GridWorld-v0', size=10)
# print(env.reset())
# print(env.action_space.sample())

import gym
import gym_examples
# import numpy as np

# Create the environment
env = gym.make('gym_examples/GridWorld-v0', size=4)

# Reset the environment to start a new episode
state = env.reset()
agent_location = env.get_agent_location()
target_location = env.get_target_location()
print(f"Agent's INITIAL Location: {agent_location}, Target Location: {target_location}")
# Initialize done to False
done = False

# Loop until the episode ends
while not done:
    # Select an action randomly
    action = env.action_space.sample()
    
    # Apply the action to the environment
    next_state, reward, done, truncated, info = env.step(action)
    
    # Optionally, render the environment to visualize it
    # env.render()
    agent_location = env.get_agent_location()
    target_location = env.get_target_location()
    print(f"Agent's Location: {agent_location}, Target Location: {target_location}")

    # Update state
    state = next_state

# Close the environment
env.close()

print("Episode finished!")


Agent's INITIAL Location: [0 3], Target Location: [0 0]
Agent's Location: [0 3], Target Location: [0 0]
Agent's Location: [0 3], Target Location: [0 0]
Agent's Location: [1 3], Target Location: [0 0]
Agent's Location: [1 3], Target Location: [0 0]
Agent's Location: [1 3], Target Location: [0 0]
Agent's Location: [1 3], Target Location: [0 0]
Agent's Location: [1 2], Target Location: [0 0]
Agent's Location: [1 2], Target Location: [0 0]
Agent's Location: [1 1], Target Location: [0 0]
Agent's Location: [1 1], Target Location: [0 0]
Agent's Location: [1 2], Target Location: [0 0]
Agent's Location: [2 2], Target Location: [0 0]
Agent's Location: [1 2], Target Location: [0 0]
Agent's Location: [1 1], Target Location: [0 0]
Agent's Location: [2 1], Target Location: [0 0]
Agent's Location: [2 0], Target Location: [0 0]
Agent's Location: [3 0], Target Location: [0 0]
Agent's Location: [3 1], Target Location: [0 0]
Agent's Location: [3 1], Target Location: [0 0]
Agent's Location: [3 2], Target 

In [9]:
env.action_space.sample()

3

In [3]:
env.step(env.action_space.sample())

({'agent': array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]),
  'target': array([0, 0])},
 -1,
 False,
 False,
 {'distance': 2.0})

In [40]:
agent_location = env.get_agent_location()

In [41]:
agent_location

array([2, 0])

In [36]:
env.

13

In [37]:
def one_hot_encode(index, vector_length=16):
    vector = np.zeros(vector_length)
    vector[index] = 1
    return vector
one_hot_encode(13)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.])

In [10]:
import gym
import gym_examples
# import numpy as np

# Create the environment
env = gym.make('gym_examples/GridWorld-v0', size=4)

# Reset the environment to start a new episode
state = env.reset()
action = env.action_space.sample()
print(action)

1


In [11]:
state

({'agent': array([3, 0]), 'target': array([0, 0])}, {'distance': 3.0})

In [12]:
next_state, reward, done, truncated, info = env.step(action)

/Users/andyyang/Desktop/DS598 Reinforcement Learning/gym-examples/.env/lib/python3.11/site-packages/gym/utils/passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


In [13]:
next_state

{'agent': array([3, 1]), 'target': array([0, 0])}

In [5]:
import gym 
import gym_examples
from dqn import Agent
import numpy as np

env = gym.make('gym_examples/GridWorld-v0', size=4)
agent = Agent(gamma=0.9, epsilon=0.5, batch_size=10, n_actions=4, eps_end=0.01, input_dims=[16], lr=0.003)
scores, eps_hist = [], []
n_games = 5

for i in range(n_games):
    score = 0
    done=False
    observation = env.reset()[0]['agent']
    counter = 0

    while not done:
        agent_location = env.get_agent_location()
        print(f"Agent's Location: {agent_location}")
        # choose an action based on current state of env
        action = agent.choose_action(observation)
        observation_, reward, done, truncated, info = env.step(action) #observation_ is just next_state
        observation_ = observation_['agent']
        score += reward
        # print(f"this is the observation:{observation_}")
        agent.store_transitions(observation, action, reward, observation_, done)
        agent.learn()
        observation = observation_
        # end of an episode
        counter += 1
        print('---')

    scores.append(score)
    eps_hist.append(agent.epsilon)
    print('end game')

    avg_score = np.mean(scores[-100:])
    


Agent's Location: [0 3]
state: tensor([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
four actions: tensor([ 0.0180,  0.0788, -0.0027,  0.1204], grad_fn=<ViewBackward0>)
selected action: 3
---
Agent's Location: [0 2]
state: tensor([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
four actions: tensor([-0.0174,  0.0785, -0.0424,  0.0629], grad_fn=<ViewBackward0>)
selected action: 1
---
Agent's Location: [0 3]
randomly selected action: 0
---
Agent's Location: [1 3]
randomly selected action: 0
---
Agent's Location: [2 3]
state: tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])
four actions: tensor([-0.0164,  0.0616, -0.0169,  0.1060], grad_fn=<ViewBackward0>)
selected action: 3
---
Agent's Location: [2 2]
randomly selected action: 1
---
Agent's Location: [2 3]
state: tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])
four actions: tensor([-0.0164,  0.0616, -0.0169,  0.1060], grad_fn=<ViewBackward0>)
selected ac

In [2]:
### TESTTTTT
import gym 
import gym_examples
from dqn import Agent
import numpy as np
import matplotlib.pyplot as plt

# Initialization
env = gym.make('gym_examples/GridWorld-v0', size=4)
n_games = 5
n_runs = 10 # Number of runs for averaging
scores_all_runs = []

for run in range(n_runs):
    agent = Agent(gamma=0.9, epsilon=0.5, batch_size=10, n_actions=4, eps_end=0.01, input_dims=[16], lr=0.003)
    scores = []
    for i in range(n_games):
        score = 0
        done = False
        observation = env.reset()[0]['agent']
        while not done:
            action = agent.choose_action(observation)
            observation_, reward, done, truncated, info = env.step(action)
            observation_ = observation_['agent']
            score += reward
            agent.store_transitions(observation, action, reward, observation_, done)
            agent.learn()
            observation = observation_
        scores.append(score)
    scores_all_runs.append(scores)

# Calculate the average scores
average_scores = np.mean(scores_all_runs, axis=0)

# Plotting
plt.plot(average_scores)
plt.xlabel('Episode')
plt.ylabel('Average Score')
plt.title('Learning Curve Averaged Over 10 Runs')
plt.show()


[]

In [15]:
import torch as T
T.tensor(observation, dtype=T.float32)

tensor([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
i

1

In [37]:
np.random.random()

0.9873709528509469

In [18]:
a = np.random.choice([1,2,3], 2, replace=False)
a

array([3, 2])

In [19]:
np.arange(2, dtype=np.int32)

array([0, 1], dtype=int32)

In [21]:
memory = np.array([1, 2, 3, 4, 5])

In [23]:
import torch as T
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np

class DeepQNetwork(nn.Module):
    def __init__(self, lr, input_dims, fc1_dims, fc2_dims, n_actions):
        super(DeepQNetwork, self).__init__()
        self.input_dims = input_dims
        self.fc1_dims = fc1_dims
        self.fc2_dims = fc2_dims
        self.n_actions = n_actions
        self.fc1 = nn.Linear(*self.input_dims, self.fc1_dims)
        self.fc2 = nn.Linear(self.fc1_dims, self.fc2_dims)
        self.fc3 = nn.Linear(self.fc2_dims, self.n_actions)
        self.optimizer = optim.Adam(self.parameters(), lr=lr)
        self.loss = F.mse_loss
        self.device = T.device('cuda:0' if T.cuda.is_available() else 'cpu')
        self.to(self.device)

    def forward(self, state):
        x = F.relu(self.fc1(state))
        x = F.relu(self.fc2(x))
        actions = self.fc3(x)

        return actions

In [24]:
net = DeepQNetwork(lr =0.003, n_actions=4, input_dims=[16], fc1_dims=128, fc2_dims=128)

In [40]:
w = net.forward(T.tensor([0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0], dtype=T.float32))
T.argmax(w).item()

2

In [34]:
memo = T.tensor([
    [0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0],
    [0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0],
    [0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0]], dtype=T.float32
)

In [36]:
actions = net.forward(memo)

In [42]:
actions

tensor([[-0.0018,  0.0231,  0.0456, -0.0359],
        [-0.0359,  0.0097,  0.0867, -0.0367],
        [-0.0359,  0.0097,  0.0867, -0.0367],
        [ 0.0365,  0.0507,  0.0973, -0.0360],
        [-0.0475,  0.0321,  0.0967, -0.0469]], grad_fn=<AddmmBackward0>)

In [41]:
T.max(actions, dim=1)[0]

tensor([0.0456, 0.0867, 0.0867, 0.0973, 0.0967], grad_fn=<MaxBackward0>)